apiVersion: v1
data:
  HTTPS_PORT: "1443"
  K8S_STATEFUL_SET_NAME: likeminds-pingdirectory
  K8S_STATEFUL_SET_SERVICE_NAME: likeminds-pingdirectory-cluster
  LDAP_PORT: "1389"
  LDAPS_PORT: "1636"
  ORCHESTRATION_TYPE: KUBERNETES
  SERVER_PROFILE_PATH: serverProfile/pingdirectory
  SERVER_PROFILE_URL: https://github.com/lmc-inc/directorypoc.git
  USER_BASE_DN: "dc=example,dc=com"
# Environment variable to enable multi-region replication
  K8S_CLUSTER: west
  K8S_CLUSTERS: west east
  K8S_POD_HOSTNAME_PREFIX: likeminds-pingdirectory-
  K8S_POD_HOSTNAME_SUFFIX: .likeminds.west.demo.likemindscloud.com
  K8S_SEED_CLUSTER: west
  K8S_SEED_HOSTNAME_SUFFIX: .likeminds.west.demo.likemindscloud.com


kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: likeminds
    app.kubernetes.io/name: pingdirectory
  name: likeminds-pingdirectory-env-vars