apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: likeminds
    app.kubernetes.io/name: pingdirectory
  name: likeminds-pingdirectory
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: likeminds
      app.kubernetes.io/name: pingdirectory
  serviceName: likeminds-pingdirectory-cluster
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: likeminds
        app.kubernetes.io/name: pingdirectory
        clusterIdentifier: likeminds-pingdirectory
    spec:
      serviceAccountName: ping-secrets-service-account
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"

      initContainers:
      - image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
        name: init-secrets-container
        command: ["/scripts/entrypoint.sh"]
        volumeMounts:
        - mountPath: /scripts
          name: pd-secrets-pull-script
        - mountPath: /var/secrets
          name: license-empty-dir
      containers:
      - envFrom:
        - configMapRef:
            name: likeminds-global-env-vars
            optional: true
        - configMapRef:
            name: likeminds-env-vars
            optional: true
        - configMapRef:
            name: likeminds-pingdirectory-env-vars
        - secretRef:
            name: devops-secret
            optional: true
        - secretRef:
            name: likeminds-pingdirectory-git-secret
            optional: true
        image: pingidentity/pingdirectory:latest
        #docker pull pingidentity/pingdirectory:2209-9.0.0.2
        #docker pull pingidentity/pingdirectory:2302
        # image: northamerica-northeast1-docker.pkg.dev/pingdirectory-358917/likeminds-pingidentity-images/pingdirectory:9.2.0.0-latest
        #docker pull pingidentity/pingdirectory:9.0.0.2-edge
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /opt/liveness.sh
          failureThreshold: 4
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: pingdirectory
        ports:
        - containerPort: 1443
          name: https
        - containerPort: 1389
          name: ldap
        - containerPort: 1636
          name: ldaps
        readinessProbe:
          exec:
            command:
            - /opt/readiness.sh
          failureThreshold: 4
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 50m
            memory: 2Gi
        startupProbe:
          exec:
            command:
            - /opt/liveness.sh
          failureThreshold: 180
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /opt/out
          name: out-dir
        - mountPath: 	/opt/in/pd.profile/server-root/pre-setup/
          name: license-empty-dir
      enableServiceLinks: true
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 9031
      terminationGracePeriodSeconds: 300
      volumes:
      - name: out-dir
        persistentVolumeClaim:
          claimName: out-dir
      - name: pd-secrets-pull-script
        configMap:
         name: pd-secrets-pull-script
         defaultMode: 0744
      - name: license-empty-dir
        emptyDir: {}
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: out-dir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi