apiVersion: v1
kind: ConfigMap
metadata:
  name: pd-secrets-pull-script
  labels:
    product: ping-directory
data:
  entrypoint.sh: |
    #!/usr/bin/env bash
    set -euo pipefail
    echo $(gcloud secrets versions access 5 --project=pingdirectory-358917 --secret=pingdirectory-license-2023) | base64 --decode >> /var/secrets/PingDirectory.lic
    