apiVersion: v1
kind: ConfigMap
metadata:
  name: pd-secrets-pull-script
  labels:
    product: ping-directory
data:
  entrypoint.sh: |
    #!/usr/bin/env bash
    #First, refresh the access token linked to the service account
    ACCESS_TOKEN=$(gcloud auth application-default print-access-token)
    export ACCESS_TOKEN
    set -euo pipefail
    #Pull the secret from secrets manager. Add a new line and script for each new secret
    echo $(gcloud secrets versions access 2 --project=pd-sandbox-project-388413 --secret=pingdirectory-license-2023) | base64 --decode >> /var/secrets/PingDirectory.lic
    