apiVersion: v1
data:
  HTTPS_PORT: "1443"
  K8S_STATEFUL_SET_NAME: likeminds-pingdirectory
  K8S_STATEFUL_SET_SERVICE_NAME: likeminds-pingdirectory-cluster-montreal
  LDAP_PORT: "1389"
  LDAPS_PORT: "1636"
  ORCHESTRATION_TYPE: KUBERNETES
  SERVER_PROFILE_PATH: serverProfile/pingdirectory
  SERVER_PROFILE_URL: https://github.com/lmc-inc/directorypoc.git
  USER_BASE_DN: "dc=example,dc=com"
# Environment variable to enable multi-region replication
  K8S_CLUSTER: montreal
  K8S_CLUSTERS: toronto montreal
  K8S_POD_HOSTNAME_PREFIX: likeminds-pingdirectory-
  K8S_POD_HOSTNAME_SUFFIX: .montreal-gke-cluster.global.likeminds-pingdirectory-cluster-montreal.ping-namespace.svc.clusterset.local.
  K8S_SEED_CLUSTER: toronto
  K8S_SEED_HOSTNAME_SUFFIX: .toronto-gke-cluster.global.likeminds-pingdirectory-cluster.ping-namespace.svc.clusterset.local.


kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: likeminds
    app.kubernetes.io/name: pingdirectory
  name: likeminds-pingdirectory-env-vars